In [1]:
!pip install sklearn
!pip install pandas

Collecting sklearn
  Using cached sklearn-0.0.post10.tar.gz (3.6 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: sklearn
  Building wheel for sklearn (pyproject.toml): started
  Building wheel for sklearn (pyproject.toml): finished with status 'done'
  Created wheel for sklearn: filename=sklearn-0.0.post10-py3-none-any.whl size=2979 sha256=169a8d49742ab94af7eef1efc0fef42cb4fa63521a336329a1919548ff226236
  Stored in directory: c:\users\eng mahmoud\appdata\local\pip\cache\wheels\3b\1f\cd\e6505747b74c9bccdec4a1d8a768960cbd49d5ba8c88a58652
Successfully built sklearn
Installing collected packages: sklearn
Successfully installed sklearn-0.0.post10

[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: pandas in c:\program files\python38\lib\site-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\program files\python38\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\program files\python38\lib\site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\program files\python38\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in c:\program files\python38\lib\site-packages (from pandas) (1.24.4)
Requirement already satisfied: six>=1.5 in c:\program files\python38\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd
c=pd.read_csv("pandas exercise/data1.csv")
c

   Duration  Pulse  Maxpulse  Calories Precentage
0        60    114       140     415.0        60%
1        60    102       127     300.0        60%
2        60    100       120     300.0        60%
3        60    100       120     300.0        60%
4        45    104       129     266.0        45%
5        45     90       112     180.1        45%
6        60     98       126     286.0        60%
7        60    100       122     329.4        60%
8        60    111       138     400.0        60%

In [3]:
duplicate=c.duplicated("Precentage",keep="last")
duplicate1=c.duplicated("Precentage",keep=False)
duplicate2=c.duplicated("Precentage",keep="first")
#default first
duplicate
c[duplicate]
#row 2 and 3 is duplicated

   Duration  Pulse  Maxpulse  Calories Precentage
0        60    114       140     415.0        60%
1        60    102       127     300.0        60%
2        60    100       120     300.0        60%
3        60    100       120     300.0        60%
4        45    104       129     266.0        45%
6        60     98       126     286.0        60%
7        60    100       122     329.4        60%

In [4]:
c[duplicate1]

   Duration  Pulse  Maxpulse  Calories Precentage
0        60    114       140     415.0        60%
1        60    102       127     300.0        60%
2        60    100       120     300.0        60%
3        60    100       120     300.0        60%
4        45    104       129     266.0        45%
5        45     90       112     180.1        45%
6        60     98       126     286.0        60%
7        60    100       122     329.4        60%
8        60    111       138     400.0        60%

In [5]:
c[duplicate2]

   Duration  Pulse  Maxpulse  Calories Precentage
1        60    102       127     300.0        60%
2        60    100       120     300.0        60%
3        60    100       120     300.0        60%
5        45     90       112     180.1        45%
6        60     98       126     286.0        60%
7        60    100       122     329.4        60%
8        60    111       138     400.0        60%

In [6]:

data=pd.read_csv("pima-indians-diabetes.csv")
print(data.to_string())

         rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
5        Prof          A   20       20    Male  122400
6   AssocProf          A   20       17    Male   81285
7        Prof          A   18       18    Male  126300
8        Prof          A   29       19    Male   94350
9        Prof          A   51       51    Male   57800
10       Prof          B   39       33    Male  128250
11       Prof          B   23       23    Male  134778
12   AsstProf          B    1        0    Male   88000
13       Prof          B   35       33    Male  162200
14       Prof          B   25       19    Male  153750
15       Prof          B   17        3    Male  150480
16   AsstProf          B    8        3    Male   75044
17   AsstProf          B    4        0    Male   92000
18       Prof          A   19        7    Male  107300
19       Prof          A   29       27    Male  150500
20   AsstProf          B    4        4    Male   92000
21       Prof          A   33       30    Male  103106
22   AsstProf          A    4        2    Male   73000
23   AsstProf          A    2        0    Male   85000
24       Prof          A   30       23    Male   91100
25       Prof          B   35       31    Male   99418
26       Prof          A   38       19    Male  148750
27       Prof          A   45       43    Male  155865
28   AsstProf          B    7        2    Male   91300
29       Prof          B   21       20    Male  123683
30  AssocProf          B    9        7    Male  107008
31       Prof          B   22       21    Male  155750
32       Prof          A   27       19    Male  103275
33       Prof          B   18       18    Male  120000
34  AssocProf          B   12        8    Male  119800
35       Prof          B   28       23    Male  126933
36       Prof          B   45       45    Male  146856
37       Prof          A   20        8    Male  102000
38   AsstProf          B    4        3    Male   91000
39       Prof          B   18       18  Female  129000
40       Prof          A   39       36  Female  137000
41  AssocProf          A   13        8  Female   74830
42   AsstProf          B    4        2  Female   80225
43   AsstProf          B    5        0  Female   77000
44       Prof          B   23       19  Female  151768
45       Prof          B   25       25  Female  140096
46   AsstProf          B   11        3  Female   74692
47  AssocProf          B   11       11  Female  103613
48       Prof          B   17       17  Female  111512
49       Prof          B   17       18  Female  122960
50   AsstProf          B   10        5  Female   97032
51       Prof          B   20       14  Female  127512
52       Prof          A   12        0  Female  105000
53   AsstProf          A    5        3  Female   73500
54  AssocProf          A   25       22  Female   62884
55   AsstProf          A    2        0  Female   72500
56  AssocProf          A   10        8  Female   77500
57   AsstProf          A    3        1  Female   72500
58       Prof          B   36       26  Female  144651
59  AssocProf          B   12       10  Female  103994
60   AsstProf          B    3        3  Female   92000
61  AssocProf          B   13       10  Female  103750
62  AssocProf          B   14        7  Female  109650
63       Prof          A   29       27  Female   91000
64  AssocProf          A   26       24  Female   73300
65       Prof          A   36       19  Female  117555
66   AsstProf          A    7        6  Female   63100
67       Prof          A   17       11  Female   90450
68   AsstProf          A    4        2  Female   77500
69       Prof          A   28        7  Female  116450
70   AsstProf          A    8        3  Female   78500
71  AssocProf          B   12        9  Female   71065
72       Prof          B   24       15  Female  161101
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

In [7]:
data.values

array([['Prof', 'B', 56, 49, 'Male', 186960],
       ['Prof', 'A', 12, 6, 'Male', 93000],
       ['Prof', 'A', 23, 20, 'Male', 110515],
       ['Prof', 'A', 40, 31, 'Male', 131205],
       ['Prof', 'B', 20, 18, 'Male', 104800],
       ['Prof', 'A', 20, 20, 'Male', 122400],
       ['AssocProf', 'A', 20, 17, 'Male', 81285],
       ['Prof', 'A', 18, 18, 'Male', 126300],
       ['Prof', 'A', 29, 19, 'Male', 94350],
       ['Prof', 'A', 51, 51, 'Male', 57800],
       ['Prof', 'B', 39, 33, 'Male', 128250],
       ['Prof', 'B', 23, 23, 'Male', 134778],
       ['AsstProf', 'B', 1, 0, 'Male', 88000],
       ['Prof', 'B', 35, 33, 'Male', 162200],
       ['Prof', 'B', 25, 19, 'Male', 153750],
       ['Prof', 'B', 17, 3, 'Male', 150480],
       ['AsstProf', 'B', 8, 3, 'Male', 75044],
       ['AsstProf', 'B', 4, 0, 'Male', 92000],
       ['Prof', 'A', 19, 7, 'Male', 107300],
       ['Prof', 'A', 29, 27, 'Male', 150500],
       ['AsstProf', 'B', 4, 4, 'Male', 92000],
       ['Prof', 'A', 33, 30, 'Male', 103106],
       ['AsstProf', 'A', 4, 2, 'Male', 73000],
       ['AsstProf', 'A', 2, 0, 'Male', 85000],
       ['Prof', 'A', 30, 23, 'Male', 91100],
       ['Prof', 'B', 35, 31, 'Male', 99418],
       ['Prof', 'A', 38, 19, 'Male', 148750],
       ['Prof', 'A', 45, 43, 'Male', 155865],
       ['AsstProf', 'B', 7, 2, 'Male', 91300],
       ['Prof', 'B', 21, 20, 'Male', 123683],
       ['AssocProf', 'B', 9, 7, 'Male', 107008],
       ['Prof', 'B', 22, 21, 'Male', 155750],
       ['Prof', 'A', 27, 19, 'Male', 103275],
       ['Prof', 'B', 18, 18, 'Male', 120000],
       ['AssocProf', 'B', 12, 8, 'Male', 119800],
       ['Prof', 'B', 28, 23, 'Male', 126933],
       ['Prof', 'B', 45, 45, 'Male', 146856],
       ['Prof', 'A', 20, 8, 'Male', 102000],
       ['AsstProf', 'B', 4, 3, 'Male', 91000],
       ['Prof', 'B', 18, 18, 'Female', 129000],
       ['Prof', 'A', 39, 36, 'Female', 137000],
       ['AssocProf', 'A', 13, 8, 'Female', 74830],
       ['AsstProf', 'B', 4, 2, 'Female', 80225],
       ['AsstProf', 'B', 5, 0, 'Female', 77000],
       ['Prof', 'B', 23, 19, 'Female', 151768],
       ['Prof', 'B', 25, 25, 'Female', 140096],
       ['AsstProf', 'B', 11, 3, 'Female', 74692],
       ['AssocProf', 'B', 11, 11, 'Female', 103613],
       ['Prof', 'B', 17, 17, 'Female', 111512],
       ['Prof', 'B', 17, 18, 'Female', 122960],
       ['AsstProf', 'B', 10, 5, 'Female', 97032],
       ['Prof', 'B', 20, 14, 'Female', 127512],
       ['Prof', 'A', 12, 0, 'Female', 105000],
       ['AsstProf', 'A', 5, 3, 'Female', 73500],
       ['AssocProf', 'A', 25, 22, 'Female', 62884],
       ['AsstProf', 'A', 2, 0, 'Female', 72500],
       ['AssocProf', 'A', 10, 8, 'Female', 77500],
       ['AsstProf', 'A', 3, 1, 'Female', 72500],
       ['Prof', 'B', 36, 26, 'Female', 144651],
       ['AssocProf', 'B', 12, 10, 'Female', 103994],
       ['AsstProf', 'B', 3, 3, 'Female', 92000],
       ['AssocProf', 'B', 13, 10, 'Female', 103750],
       ['AssocProf', 'B', 14, 7, 'Female', 109650],
       ['Prof', 'A', 29, 27, 'Female', 91000],
       ['AssocProf', 'A', 26, 24, 'Female', 73300],
       ['Prof', 'A', 36, 19, 'Female', 117555],
       ['AsstProf', 'A', 7, 6, 'Female', 63100],
       ['Prof', 'A', 17, 11, 'Female', 90450],
       ['AsstProf', 'A', 4, 2, 'Female', 77500],
       ['Prof', 'A', 28, 7, 'Female', 116450],
       ['AsstProf', 'A', 8, 3, 'Female', 78500],
       ['AssocProf', 'B', 12, 9, 'Female', 71065],
       ['Prof', 'B', 24, 15, 'Female', 161101],
       ['Prof', 'B', 18, 10, 'Female', 105450],
       ['AssocProf', 'B', 19, 6, 'Female', 104542],
       ['Prof', 'B', 17, 17, 'Female', 124312],
       ['Prof', 'A', 28, 14, 'Female', 109954],
       ['Prof', 'A', 23, 15, 'Female', 109646]], dtype=object)

In [8]:
ee=data.to_dict()
ee

{'rank': {0: 'Prof',
  1: 'Prof',
  2: 'Prof',
  3: 'Prof',
  4: 'Prof',
  5: 'Prof',
  6: 'AssocProf',
  7: 'Prof',
  8: 'Prof',
  9: 'Prof',
  10: 'Prof',
  11: 'Prof',
  12: 'AsstProf',
  13: 'Prof',
  14: 'Prof',
  15: 'Prof',
  16: 'AsstProf',
  17: 'AsstProf',
  18: 'Prof',
  19: 'Prof',
  20: 'AsstProf',
  21: 'Prof',
  22: 'AsstProf',
  23: 'AsstProf',
  24: 'Prof',
  25: 'Prof',
  26: 'Prof',
  27: 'Prof',
  28: 'AsstProf',
  29: 'Prof',
  30: 'AssocProf',
  31: 'Prof',
  32: 'Prof',
  33: 'Prof',
  34: 'AssocProf',
  35: 'Prof',
  36: 'Prof',
  37: 'Prof',
  38: 'AsstProf',
  39: 'Prof',
  40: 'Prof',
  41: 'AssocProf',
  42: 'AsstProf',
  43: 'AsstProf',
  44: 'Prof',
  45: 'Prof',
  46: 'AsstProf',
  47: 'AssocProf',
  48: 'Prof',
  49: 'Prof',
  50: 'AsstProf',
  51: 'Prof',
  52: 'Prof',
  53: 'AsstProf',
  54: 'AssocProf',
  55: 'AsstProf',
  56: 'AssocProf',
  57: 'AsstProf',
  58: 'Prof',
  59: 'AssocProf',
  60: 'AsstProf',
  61: 'AssocProf',
  62: 'AssocProf',
  63: 'Prof',
  64: 'AssocProf',
  65: 'Prof',
  66: 'AsstProf',
  67: 'Prof',
  68: 'AsstProf',
  69: 'Prof',
  70: 'AsstProf',
  71: 'AssocProf',
  72: 'Prof',
  73: 'Prof',
  74: 'AssocProf',
  75: 'Prof',
  76: 'Prof',
  77: 'Prof'},
 'discipline': {0: 'B',
  1: 'A',
  2: 'A',
  3: 'A',
  4: 'B',
  5: 'A',
  6: 'A',
  7: 'A',
  8: 'A',
  9: 'A',
  10: 'B',
  11: 'B',
  12: 'B',
  13: 'B',
  14: 'B',
  15: 'B',
  16: 'B',
  17: 'B',
  18: 'A',
  19: 'A',
  20: 'B',
  21: 'A',
  22: 'A',
  23: 'A',
  24: 'A',
  25: 'B',
  26: 'A',
  27: 'A',
  28: 'B',
  29: 'B',
  30: 'B',
  31: 'B',
  32: 'A',
  33: 'B',
  34: 'B',
  35: 'B',
  36: 'B',
  37: 'A',
  38: 'B',
  39: 'B',
  40: 'A',
  41: 'A',
  42: 'B',
  43: 'B',
  44: 'B',
  45: 'B',
  46: 'B',
  47: 'B',
  48: 'B',
  49: 'B',
  50: 'B',
  51: 'B',
  52: 'A',
  53: 'A',
  54: 'A',
  55: 'A',
  56: 'A',
  57: 'A',
  58: 'B',
  59: 'B',
  60: 'B',
  61: 'B',
  62: 'B',
  63: 'A',
  64: 'A',
  65: 'A',
  66: 'A',
  67: 'A',
  68: 'A',
  69: 'A',
  70: 'A',
  71: 'B',
  72: 'B',
  73: 'B',
  74: 'B',
  75: 'B',
  76: 'A',
  77: 'A'},
 'phd': {0: 56,
  1: 12,
  2: 23,
  3: 40,
  4: 20,
  5: 20,
  6: 20,
  7: 18,
  8: 29,
  9: 51,
  10: 39,
  11: 23,
  12: 1,
  13: 35,
  14: 25,
  15: 17,
  16: 8,
  17: 4,
  18: 19,
  19: 29,
  20: 4,
  21: 33,
  22: 4,
  23: 2,
  24: 30,
  25: 35,
  26: 38,
  27: 45,
  28: 7,
  29: 21,
  30: 9,
  31: 22,
  32: 27,
  33: 18,
  34: 12,
  35: 28,
  36: 45,
  37: 20,
  38: 4,
  39: 18,
  40: 39,
  41: 13,
  42: 4,
  43: 5,
  44: 23,
  45: 25,
  46: 11,
  47: 11,
  48: 17,
  49: 17,
  50: 10,
  51: 20,
  52: 12,
  53: 5,
  54: 25,
  55: 2,
  56: 10,
  57: 3,
  58: 36,
  59: 12,
  60: 3,
  61: 13,
  62: 14,
  63: 29,
  64: 26,
  65: 36,
  66: 7,
  67: 17,
  68: 4,
  69: 28,
  70: 8,
  71: 12,
  72: 24,
  73: 18,
  74: 19,
  75: 17,
  76: 28,
  77: 23},
 'service': {0: 49,
  1: 6,
  2: 20,
  3: 31,
  4: 18,
  5: 20,
  6: 17,
  7: 18,
  8: 19,
  9: 51,
  10: 33,
  11: 23,
  12: 0,
  13: 33,
  14: 19,
  15: 3,
  16: 3,
  17: 0,
  18: 7,
  19: 27,
  20: 4,
  21: 30,
  22: 2,
  23: 0,
  24: 23,
  25: 31,
  26: 19,
  27: 43,
  28: 2,
  29: 20,
  30: 7,
  31: 21,
  32: 19,
  33: 18,
  34: 8,
  35: 23,
  36: 45,
  37: 8,
  38: 3,
  39: 18,
  40: 36,
  41: 8,
  42: 2,
  43: 0,
  44: 19,
  45: 25,
  46: 3,
  47: 11,
  48: 17,
  49: 18,
  50: 5,
  51: 14,
  52: 0,
  53: 3,
  54: 22,
  55: 0,
  56: 8,
  57: 1,
  58: 26,
  59: 10,
  60: 3,
  61: 10,
  62: 7,
  63: 27,
  64: 24,
  65: 19,
  66: 6,
  67: 11,
  68: 2,
  69: 7,
  70: 3,
  71: 9,
  72: 15,
  73: 10,
  74: 6,
  75: 17,
  76: 14,
  77: 15},
 'sex': {0: 'Male',
  1: 'Male',
  2: 'Male',
  3: 'Male',
  4: 'Male',
  5: 'Male',
  6: 'Male',
  7: 'Male',
  8: 'Male',
  9: 'Male',
  10: 'Male',
  11: 'Male',
  12: 'Male',
  13: 'Male',
  14: 'Male',
  15: 'Male',
  16: 'Male',
  17: 'Male',
  18: 'Male',
  19: 'Male',
  20: 'Male',
  21: 'Male',
  22: 'Male',
  23: 'Male',
  24: 'Male',
  25: 'Male',
  26: 'Male',
  27: 'Male',
  28: 'Male',
  29: 'Male',
  30: 'Male',
  31: 'Male',
  32: 'Male',
  33: 'Male',
  34: 'Male',
  35: 'Male',
  36: 'Male',
  37: 'Male',
  38: 'Male',
  39: 'Female',
  40: 'Female',
  41: 'Female',
  42: 'Female',
  43: 'Female',
  44: 'Female',
  45: 'Female',
  46: 'Female',
  47: 'Female',
  48: 'Female',
  49: 'Female',
  50: 'Female',
  51: 'Female',
  52: 'Female',
  53: 'Female',
  54: 'Female',
  55: 'Female',
  56: 'Female',
  57: 'Female',
  58: 'Female',
  59: 'Female',
  60: 'Female',
  61: 'Female',
  62: 'Female',
  63: 'Female',
  64: 'Female',
  65: 'Female',
  66: 'Female',
  67: 'Female',
  68: 'Female',
  69: 'Female',
  70: 'Female',
  71: 'Female',
  72: 'Female',
  73: 'Female',
  74: 'Female',
  75: 'Female',
  76: 'Female',
  77: 'Female'},
 'salary': {0: 186960,
  1: 93000,
  2: 110515,
  3: 131205,
  4: 104800,
  5: 122400,
  6: 81285,
  7: 126300,
  8: 94350,
  9: 57800,
  10: 128250,
  11: 134778,
  12: 88000,
  13: 162200,
  14: 153750,
  15: 150480,
  16: 75044,
  17: 92000,
  18: 107300,
  19: 150500,
  20: 92000,
  21: 103106,
  22: 73000,
  23: 85000,
  24: 91100,
  25: 99418,
  26: 148750,
  27: 155865,
  28: 91300,
  29: 123683,
  30: 107008,
  31: 155750,
  32: 103275,
  33: 120000,
  34: 119800,
  35: 126933,
  36: 146856,
  37: 102000,
  38: 91000,
  39: 129000,
  40: 137000,
  41: 74830,
  42: 80225,
  43: 77000,
  44: 151768,
  45: 140096,
  46: 74692,
  47: 103613,
  48: 111512,
  49: 122960,
  50: 97032,
  51: 127512,
  52: 105000,
  53: 73500,
  54: 62884,
  55: 72500,
  56: 77500,
  57: 72500,
  58: 144651,
  59: 103994,
  60: 92000,
  61: 103750,
  62: 109650,
  63: 91000,
  64: 73300,
  65: 117555,
  66: 63100,
  67: 90450,
  68: 77500,
  69: 116450,
  70: 78500,
  71: 71065,
  72: 161101,
  73: 105450,
  74: 104542,
  75: 124312,
  76: 109954,
  77: 109646}}

In [14]:
! pip install --upgrade pip
!pip install sklearn
from sklearn import preprocessing
data1=preprocessing.MinMaxScalar(feature_range=(0,1))

Requirement already satisfied: pip in c:\program files\python38\lib\site-packages (23.2.1)
Collecting pip
  Obtaining dependency information for pip from https://files.pythonhosted.org/packages/47/6a/453160888fab7c6a432a6e25f8afe6256d0d9f2cbd25971021da6491d899/pip-23.3.1-py3-none-any.whl.metadata
  Using cached pip-23.3.1-py3-none-any.whl.metadata (3.5 kB)
Using cached pip-23.3.1-py3-none-any.whl (2.1 MB)

ERROR: To modify pip, please run the following command:
c:\program files\python38\python.exe -m pip install --upgrade pip

[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: sklearn in c:\program files\python38\lib\site-packages (0.0.post10)

[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

ModuleNotFoundError: No module named 'sklearn'